require:
  - rubocop-rails
  # TODO: add rubocop-rspec

AllCops:
  NewCops: enable

Rails/FilePath:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
